Implemented B

diff --git a/bin/gi b/bin/gi
--- a/bin/gi
+++ b/bin/gi
@@ -4,26 +4,18 @@ echoerr() {
 	echo "$@" 1>&2;
 }
 COMMAND=$1
+
+if [[ "${COMMAND}" == 'open' && $2 =~ ^[0-9]+$ && $# == 2 ]]; then
+	echo "[ERROR] - Opening a new issue with a numeric name not advised";echo
+	exit 128
+fi
+
 if [ `uname` == 'Darwin' ]; then
 	script=$(greadlink -f "$0")
 else
 	script=$(readlink -f "$0")
 fi
 DIR_ROOT=$(dirname $script)/../
-
-case "${COMMAND}" in
-	'co' ) COMMAND='checkout' ;;
-	'li' ) COMMAND='list' ;;
-	'det' ) COMMAND='details' ;;
-	'pr' ) COMMAND='pull-request' ;;
-	'new' ) COMMAND='open' ;;
-	'open' )
-		if [[  $2 =~ ^[0-9]+$ && $# == 2 ]]; then
-        	echo;echo "*** Please consider typing co or checkout instead of open next time";echo
-        	COMMAND='checkout'
-        fi
-     ;;
-esac
 
 if ! (test -e $DIR_ROOT"commands/"$COMMAND); then
 	echoerr "Invalid command '$COMMAND'.";
