Saying what's to be said on STDERR

diff --git a/commands/open b/commands/open
--- a/commands/open
+++ b/commands/open
@@ -1,7 +1,7 @@
 #!/bin/bash -e
 
 if [[ $1 =~ ^[0-9]+$ && $# == 1 ]]; then
-	echo $'[ERROR] - Opening a new issue with a numeric name not supported\n'
+	echo $'[ERROR] - Opening a new issue with a numeric name not supported\n' 1>&2
 	exit 127
 fi
 
